user nginx;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


# Load all installed modules
#include modules.d/*.conf;

events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    gzip  on;

    server {
        listen       80;
        server_name  3urobeat.com;

        #access_log  logs/host.access.log  main;

        location / {
            root   /usr/share/nginx/html/;
            index  index.html;
        }

        location /linktree {
            root /usr/share/nginx/html;
            try_files /linktree.html =404;
        }

        # Redirect error pages to index
        location @indexredirect {
            return 302 /;
        }

        error_page 400 = @indexredirect;
        error_page 403 = @indexredirect;
        error_page 404 = @indexredirect;
        error_page 500 = @indexredirect;

        # Disable unnecessary methods
        if ($request_method !~ ^(GET|HEAD|POST)$ ) {
            return 405;
        }
    }

}
